//
//  UIView+AutoLayout-Deprecated.h
//
//  Created by Liam Nichols on 24/04/2014.

/** Deprecated methods are listed here.
 
 All methods listed in this document have been deprecated. The below documentation will provide instructions on how to migrate to the newer more flexible methods.
 
 @warning Deprecated methods will be removed in future releases.
 */

@interface UIView (AutoLayoutDeprecated)

/** @name Pinning Attributes of Views */

/**
 *  Pin an attribute to the same attribute on another view. Both views must be in the same view hierarchy.
 *  @deprecated use pinAttribute:toSameAttributeOfItem: instead
 *
 *  @param attribute The attribute of the receiver that you want to pin to the `peerView`.
 *  @param peerView  The view you want to pin the receiver to.
 *
 *  @return The constraint generated by this method.
 */
-(NSLayoutConstraint *)pinAttribute:(NSLayoutAttribute)attribute toSameAttributeOfView:(UIView *)peerView DEPRECATED_MSG_ATTRIBUTE("use pinAttribute:toSameAttributeOfItem: instead");


/** @name Pinning Edges of Views */


/**
 *  Pins a view's edge to a peer view's edge. Both views must be in the same view hierarchy.
 *  @deprecated use pinAttribute:toAttribute:ofItem: instead
 *
 *  @param edge     The edge of the receiver that you want to pin.
 *  @param toEdge   The edge of the `peerView` that you want to pin
 *  @param peerView The view that you want to pin the receiver to.
 *
 *  @return The constraint generated by this method.
 */
-(NSLayoutConstraint *)pinEdge:(NSLayoutAttribute)edge toEdge:(NSLayoutAttribute)toEdge ofView:(UIView*)peerView DEPRECATED_MSG_ATTRIBUTE("use pinAttribute:toAttribute:ofItem: instead");

/**
 *  Pins a view's edge to a peer view's edge, with an inset. Both views must be in the same view hierarchy.
 *  @deprecated use pinAttribute:toAttribute:ofItem:withConstant: instead
 *
 *  @param edge     The edge of the receiver that you want to pin.
 *  @param toEdge   The edge of the `peerView` that you want to pin
 *  @param peerView The view that you want to pin the receiver to.
 *  @param inset    The inset that you want to apply to the constraint
 *
 *  @return The constraint generated by this method.
 */
-(NSLayoutConstraint *)pinEdge:(NSLayoutAttribute)edge toEdge:(NSLayoutAttribute)toEdge ofView:(UIView *)peerView inset:(CGFloat)inset DEPRECATED_MSG_ATTRIBUTE("use pinAttribute:toAttribute:ofItem:withConstant: instead");

/**
 *  Pins a view's edge to a peer item's edge. The item may be the layout guide of a view controller
 *  @deprecated use pinAttribute:toAttribute:ofItem instead
 *
 *  @param edge     The edge of the receiver that you want to pin.
 *  @param toEdge   The edge of the `peerView` that you want to pin
 *  @param peerItem The view that you want to pin the receiver to.
 *
 *  @return The constraint generated by this method.
 */
-(NSLayoutConstraint *)pinEdge:(NSLayoutAttribute)edge toEdge:(NSLayoutAttribute)toEdge ofItem:(id)peerItem DEPRECATED_MSG_ATTRIBUTE("use pinAttribute:toAttribute:ofItem instead");

/**
 *  Pins a view's edge to a peer item's edge, with an inset. The item may be the layout guide of a view controller
 *  @deprecated use pinAttribute:toAttribute:ofItem:withConstant: instead
 *
 *  @param edge     The edge of the receiver that you want to pin.
 *  @param toEdge   The edge of the `peerView` that you want to pin
 *  @param peerItem The view that you want to pin the receiver to.
 *  @param inset    The inset that you want to apply to the constraint
 *
 *  @return The constraint generated by this method.
 */
-(NSLayoutConstraint *)pinEdge:(NSLayoutAttribute)edge toEdge:(NSLayoutAttribute)toEdge ofItem:(id)peerItem inset:(CGFloat)inset DEPRECATED_MSG_ATTRIBUTE("use pinAttribute:toAttribute:ofItem:withConstant: instead");

/**
 *  Pins a view's edge to a peer item's edge, with an inset and a specific relation. The item may be the layout guide of a view controller.
 *  @deprecated use pinAttribute:toAttribute:ofItem:withConstant:relation: instead
 *
 *  @param edge     The edge of the receiver that you want to pin.
 *  @param toEdge   The edge of the `peerView` that you want to pin
 *  @param peerItem The view that you want to pin the receiver to.
 *  @param inset    The inset that you want to apply to the constraint
 *  @param relation The relation that you wish to apply to the constraint
 *
 *  @return The constraint generated by this method.
 */
-(NSLayoutConstraint *)pinEdge:(NSLayoutAttribute)edge toEdge:(NSLayoutAttribute)toEdge ofItem:(id)peerItem inset:(CGFloat)inset relation:(NSLayoutRelation)relation DEPRECATED_MSG_ATTRIBUTE("use pinAttribute:toAttribute:ofItem:withConstant:relation: instead");

@end